import { Category, Wish } from '../daisybomTypes';

export const TASKS: Record<Category, string[]> = {
  sport: [
    "Try to reach the floor with your foot without bending your knee.",
    "Stand on one leg for 30 seconds.",
    "Do 10 jumping jacks.",
    "Touch your toes without bending your knees.",
    "Do a handstand (or try to!).",
    "Run in place for 20 seconds.",
    "Do 5 push-ups.",
    "Balance on one foot with your eyes closed.",
    "Do a cartwheel (or try to!).",
    "Jump as high as you can 5 times.",
    "Do a plank for 30 seconds.",
    "Touch your nose with your tongue.",
    "Do 10 squats.",
    "Stand on your tiptoes for 20 seconds.",
    "Do a somersault.",
  ],
  animals: [
    "Jump like a frog 5 times.",
    "Walk like a penguin across the room.",
    "Roar like a lion 3 times.",
    "Hop like a bunny 10 times.",
    "Crawl like a bear.",
    "Flap your arms like a bird for 10 seconds.",
    "Move like a snake on the floor.",
    "Stretch like a cat.",
    "Make monkey sounds for 10 seconds.",
    "Walk like a crab.",
    "Imitate a dog wagging its tail.",
    "Move like a fish out of water.",
    "Hop like a kangaroo.",
    "Make elephant sounds.",
    "Move like a spider.",
  ],
  dance: [
    "Dance to imaginary music for 30 seconds.",
    "Do the robot dance.",
    "Dance like nobody's watching for 20 seconds.",
    "Do a breakdance move (or try to!).",
    "Dance with your eyes closed.",
    "Do the moonwalk (or try to!).",
    "Dance like you're in a music video.",
    "Do a spin and keep your balance.",
    "Dance with only one arm moving.",
    "Do a dance move you've never done before.",
    "Dance in slow motion for 20 seconds.",
    "Do a dance move from the 80s.",
    "Dance like you're underwater.",
    "Do a dance move with your hands only.",
    "Dance like you're on stage.",
  ],
};

export const WISHES: Wish[] = [
  { id: '1', text: "Sing a part of any song like you're on stage.", isDefault: true },
  { id: '2', text: "Do a funny dance for 30 seconds.", isDefault: true },
  { id: '3', text: "Tell a joke that makes everyone laugh.", isDefault: true },
  { id: '4', text: "Imitate a famous person for 1 minute.", isDefault: true },
  { id: '5', text: "Do 20 push-ups.", isDefault: true },
  { id: '6', text: "Sing a song in a funny voice.", isDefault: true },
  { id: '7', text: "Do a cartwheel (or try to!).", isDefault: true },
  { id: '8', text: "Tell a story about your most embarrassing moment.", isDefault: true },
  { id: '9', text: "Do an impression of the other player.", isDefault: true },
  { id: '10', text: "Eat something spicy (if available).", isDefault: true },
  { id: '11', text: "Do a handstand (or try to!).", isDefault: true },
  { id: '12', text: "Sing a song in a different language.", isDefault: true },
  { id: '13', text: "Do a funny face and hold it for 10 seconds.", isDefault: true },
  { id: '14', text: "Tell everyone your biggest secret (make it fun!).", isDefault: true },
  { id: '15', text: "Do your best impression of a celebrity.", isDefault: true },
];

export const DAISY_MESSAGES = {
  home: "Hello friends! Are you ready to have a great time?",
  addPlayer: "Hello friends! Choose your players and prepare for a new duel",
  chooseCategory: "Choose the category you like!",
  wishlist: "I offer you a list of wishes! Choose the one that suits you.",
  round: "Good luck! You can do it!",
  results: "Congratulations! You both did great!",
  settings: "Customize your game experience!",
  about: "Thank you for playing Daisybom: Duel Party!",
};

